language: node_js
env:
  matrix:
  - CI=true
  global:
    secure: "BqwfHv/op/227TSe4T6MtZrhef9/J6YyGM2mhgvAs0TPa3L8RpCUglORJwGfSFfvdEG18UV8VRyhLSng1/ItlrN5PaAS7nJf9PHj+g8ezG6d0R7Kak56jJa9itaoOiS6c4K21n1ICeXKL/tP2zQXxhVwQeDavfLxfepyfdGqK7Y="
sudo: false
node_js:
- '12'

install:
- npm install

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
script:
- npm test
- npm run build
- npm run chromatic
- fossa init
- fossa analyze
